name: CI/CD
on: 
  workflow_dispatch:
 
jobs:
 wsl-jobs:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
         com: [1]
    continue-on-error: true
    defaults:
      run:
          shell: wsl-run {0}
    steps:
      - name: Setup
        env:
            wsl_conf: ${{ secrets.WSL_CONFIG }}
        run: |
          echo "The secret value (masked): %wsl_conf%"
        shell: pwsh
